#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasesAvanzadas.MVVM.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LearnHub")]
	public partial class CoursesDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcurso(curso instance);
    partial void Updatecurso(curso instance);
    partial void Deletecurso(curso instance);
    partial void Insertmateria(materia instance);
    partial void Updatemateria(materia instance);
    partial void Deletemateria(materia instance);
    #endregion
		
		public CoursesDBDataContext() : 
				base(global::BasesAvanzadas.Properties.Settings.Default.LearnHubConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CoursesDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoursesDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoursesDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoursesDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<curso> cursos
		{
			get
			{
				return this.GetTable<curso>();
			}
		}
		
		public System.Data.Linq.Table<materia> materias
		{
			get
			{
				return this.GetTable<materia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cursos")]
	public partial class curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_curso;
		
		private string _nombre_del_curso;
		
		private int _Duracion__Horas_;
		
		private int _materias_id_materia;
		
		private int _profesor_id_profesor;
		
		private string _descripcion;
		
		private int _estudiantes_id_estudiante;
		
		private EntityRef<materia> _materia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cursoChanging(int value);
    partial void Onid_cursoChanged();
    partial void Onnombre_del_cursoChanging(string value);
    partial void Onnombre_del_cursoChanged();
    partial void OnDuracion__Horas_Changing(int value);
    partial void OnDuracion__Horas_Changed();
    partial void Onmaterias_id_materiaChanging(int value);
    partial void Onmaterias_id_materiaChanged();
    partial void Onprofesor_id_profesorChanging(int value);
    partial void Onprofesor_id_profesorChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onestudiantes_id_estudianteChanging(int value);
    partial void Onestudiantes_id_estudianteChanged();
    #endregion
		
		public curso()
		{
			this._materia = default(EntityRef<materia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_curso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_curso
		{
			get
			{
				return this._id_curso;
			}
			set
			{
				if ((this._id_curso != value))
				{
					this.Onid_cursoChanging(value);
					this.SendPropertyChanging();
					this._id_curso = value;
					this.SendPropertyChanged("id_curso");
					this.Onid_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_del_curso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_del_curso
		{
			get
			{
				return this._nombre_del_curso;
			}
			set
			{
				if ((this._nombre_del_curso != value))
				{
					this.Onnombre_del_cursoChanging(value);
					this.SendPropertyChanging();
					this._nombre_del_curso = value;
					this.SendPropertyChanged("nombre_del_curso");
					this.Onnombre_del_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Duracion_(Horas)]", Storage="_Duracion__Horas_", DbType="Int NOT NULL")]
		public int Duracion__Horas_
		{
			get
			{
				return this._Duracion__Horas_;
			}
			set
			{
				if ((this._Duracion__Horas_ != value))
				{
					this.OnDuracion__Horas_Changing(value);
					this.SendPropertyChanging();
					this._Duracion__Horas_ = value;
					this.SendPropertyChanged("Duracion__Horas_");
					this.OnDuracion__Horas_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materias_id_materia", DbType="Int NOT NULL")]
		public int materias_id_materia
		{
			get
			{
				return this._materias_id_materia;
			}
			set
			{
				if ((this._materias_id_materia != value))
				{
					if (this._materia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmaterias_id_materiaChanging(value);
					this.SendPropertyChanging();
					this._materias_id_materia = value;
					this.SendPropertyChanged("materias_id_materia");
					this.Onmaterias_id_materiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesor_id_profesor", DbType="Int NOT NULL")]
		public int profesor_id_profesor
		{
			get
			{
				return this._profesor_id_profesor;
			}
			set
			{
				if ((this._profesor_id_profesor != value))
				{
					this.Onprofesor_id_profesorChanging(value);
					this.SendPropertyChanging();
					this._profesor_id_profesor = value;
					this.SendPropertyChanged("profesor_id_profesor");
					this.Onprofesor_id_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estudiantes_id_estudiante", DbType="Int NOT NULL")]
		public int estudiantes_id_estudiante
		{
			get
			{
				return this._estudiantes_id_estudiante;
			}
			set
			{
				if ((this._estudiantes_id_estudiante != value))
				{
					this.Onestudiantes_id_estudianteChanging(value);
					this.SendPropertyChanging();
					this._estudiantes_id_estudiante = value;
					this.SendPropertyChanged("estudiantes_id_estudiante");
					this.Onestudiantes_id_estudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="materia_curso", Storage="_materia", ThisKey="materias_id_materia", OtherKey="id_materia", IsForeignKey=true)]
		public materia materia
		{
			get
			{
				return this._materia.Entity;
			}
			set
			{
				materia previousValue = this._materia.Entity;
				if (((previousValue != value) 
							|| (this._materia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._materia.Entity = null;
						previousValue.cursos.Remove(this);
					}
					this._materia.Entity = value;
					if ((value != null))
					{
						value.cursos.Add(this);
						this._materias_id_materia = value.id_materia;
					}
					else
					{
						this._materias_id_materia = default(int);
					}
					this.SendPropertyChanged("materia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.materias")]
	public partial class materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_materia;
		
		private string _materia1;
		
		private EntitySet<curso> _cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_materiaChanging(int value);
    partial void Onid_materiaChanged();
    partial void Onmateria1Changing(string value);
    partial void Onmateria1Changed();
    #endregion
		
		public materia()
		{
			this._cursos = new EntitySet<curso>(new Action<curso>(this.attach_cursos), new Action<curso>(this.detach_cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_materia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_materia
		{
			get
			{
				return this._id_materia;
			}
			set
			{
				if ((this._id_materia != value))
				{
					this.Onid_materiaChanging(value);
					this.SendPropertyChanging();
					this._id_materia = value;
					this.SendPropertyChanged("id_materia");
					this.Onid_materiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="materia", Storage="_materia1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string materia1
		{
			get
			{
				return this._materia1;
			}
			set
			{
				if ((this._materia1 != value))
				{
					this.Onmateria1Changing(value);
					this.SendPropertyChanging();
					this._materia1 = value;
					this.SendPropertyChanged("materia1");
					this.Onmateria1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="materia_curso", Storage="_cursos", ThisKey="id_materia", OtherKey="materias_id_materia")]
		public EntitySet<curso> cursos
		{
			get
			{
				return this._cursos;
			}
			set
			{
				this._cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cursos(curso entity)
		{
			this.SendPropertyChanging();
			entity.materia = this;
		}
		
		private void detach_cursos(curso entity)
		{
			this.SendPropertyChanging();
			entity.materia = null;
		}
	}
}
#pragma warning restore 1591
