<?xml version="1.0" encoding="utf-8"?><Database Name="LearnHub" Class="LoginDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC-PACO;Initial Catalog=LearnHub;Integrated Security=True" SettingsObjectName="BasesAvanzadas.Properties.Settings" SettingsPropertyName="LearnHubConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.estudiantes" Member="estudiantes">
    <Type Name="estudiante">
      <Column Name="id_estudiante" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Nombre(s)]" Member="Nombre_s_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Apellido(s)]" Member="Apellido_s_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.profesor" Member="profesors">
    <Type Name="profesor">
      <Column Name="id_profesor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Nombre(s)]" Member="Nombre_s_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Apellido(s)]" Member="Apellido_s_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cursos_id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>